import os

ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY")
ANTHROPIC_MODEL = os.environ.get("ANTHROPIC_MODEL", "claude-sonnet-4-6")

AZURE_DOC_INTEL_ENDPOINT = os.environ.get("AZURE_DOC_INTEL_ENDPOINT")
AZURE_DOC_INTEL_KEY = os.environ.get("AZURE_DOC_INTEL_KEY")

USE_REAL_LLM = bool(ANTHROPIC_API_KEY)
USE_REAL_AZURE_VISION = bool(AZURE_DOC_INTEL_ENDPOINT and AZURE_DOC_INTEL_KEY)

OUTPUT_DIR = os.environ.get("REPORT_OUTPUT_DIR", "outputs")
