from __future__ import annotations
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH


def _add_heading(doc, text, level=1):
    h = doc.add_heading(level=level)
    run = h.add_run(text)
    run.font.color.rgb = RGBColor(0x1B, 0x2A, 0x4A)
    return h


def _add_bullets(doc, items):
    for item in items:
        doc.add_paragraph(item, style="List Bullet")


def build_docx(state: dict, output_path: str) -> str:
    doc = Document()

    title = doc.add_heading(level=0)
    run = title.add_run("Quarterly Business Report")
    run.font.color.rgb = RGBColor(0x1B, 0x2A, 0x4A)
    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.LEFT
    sub_run = subtitle.add_run("Auto-generated by multi-agent GenAI pipeline")
    sub_run.italic = True
    sub_run.font.size = Pt(11)

    kpis = state.get("kpis", {})
    _add_heading(doc, "Key Performance Indicators", level=1)
    table = doc.add_table(rows=1, cols=2)
    table.style = "Light Grid Accent 1"
    hdr = table.rows[0].cells
    hdr[0].text, hdr[1].text = "Metric", "Value"

    rows = [
        ("Total Revenue", f"${kpis.get('total_revenue', 0):,}"),
        ("Total Units Sold", f"{kpis.get('total_units_sold', 0):,}"),
        ("Q1→Q4 Revenue Growth", f"{kpis.get('q1_to_q4_revenue_growth_pct', 'N/A')}%"),
        ("Top Region by Revenue", kpis.get("top_region_by_revenue", "N/A")),
        ("Top Region by Net Customer Growth", kpis.get("top_region_by_net_growth", "N/A")),
    ]
    for label, value in rows:
        cells = table.add_row().cells
        cells[0].text, cells[1].text = label, str(value)

    if state.get("data_findings"):
        _add_heading(doc, "Data Findings", level=1)
        _add_bullets(doc, state["data_findings"])

    if state.get("vision_findings"):
        _add_heading(doc, "Chart & Document Findings", level=1)
        _add_bullets(doc, state["vision_findings"])

    if state.get("inferences"):
        _add_heading(doc, "Inferences & Recommendations", level=1)
        _add_bullets(doc, state["inferences"])

    doc.save(output_path)
    return output_path
