from __future__ import annotations
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN

NAVY = RGBColor(0x1B, 0x2A, 0x4A)
ACCENT = RGBColor(0x2E, 0x86, 0xAB)
GRAY = RGBColor(0x5A, 0x5A, 0x5A)


def _set_run(run, text, size=18, color=GRAY, bold=False):
    run.text = text
    run.font.size = Pt(size)
    run.font.color.rgb = color
    run.font.bold = bold


def _add_title_slide(prs, title, subtitle):
    slide = prs.slides.add_slide(prs.slide_layouts[6])  # blank layout
    box = slide.shapes.add_textbox(Inches(0.7), Inches(2.3), Inches(8.6), Inches(1.2))
    tf = box.text_frame
    _set_run(tf.paragraphs[0].add_run(), title, size=36, color=NAVY, bold=True)

    box2 = slide.shapes.add_textbox(Inches(0.7), Inches(3.3), Inches(8.6), Inches(0.6))
    tf2 = box2.text_frame
    _set_run(tf2.paragraphs[0].add_run(), subtitle, size=16, color=ACCENT)
    return slide


def _add_bullet_slide(prs, title, bullets):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    title_box = slide.shapes.add_textbox(Inches(0.6), Inches(0.4), Inches(9.0), Inches(0.8))
    _set_run(title_box.text_frame.paragraphs[0].add_run(), title, size=26, color=NAVY, bold=True)

    body_box = slide.shapes.add_textbox(Inches(0.7), Inches(1.4), Inches(8.6), Inches(4.8))
    tf = body_box.text_frame
    tf.word_wrap = True
    for i, bullet in enumerate(bullets):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.text = ""  # cleared, then set via run to preserve control over formatting
        run = p.add_run()
        _set_run(run, f"•  {bullet}", size=16, color=GRAY)
        p.space_after = Pt(10)
    return slide


def _add_kpi_slide(prs, title, kpi_items):
    """kpi_items: list of (label, value) tuples, rendered as simple KPI cards."""
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    title_box = slide.shapes.add_textbox(Inches(0.6), Inches(0.4), Inches(9.0), Inches(0.8))
    _set_run(title_box.text_frame.paragraphs[0].add_run(), title, size=26, color=NAVY, bold=True)

    n = len(kpi_items)
    slide_width_in = 10.0
    margin_in = 0.6
    gap_in = 0.25
    available_in = slide_width_in - (2 * margin_in) - (gap_in * (n - 1))
    card_w_in = available_in / n
    card_w = Inches(card_w_in)
    gap = Inches(gap_in)
    start_x = Inches(margin_in)
    y = Inches(1.7)
    for i, (label, value) in enumerate(kpi_items):
        x = start_x + i * (card_w + gap)
        card = slide.shapes.add_shape(1, x, y, card_w, Inches(1.8))  # 1 = MSO_SHAPE.RECTANGLE
        card.fill.solid()
        card.fill.fore_color.rgb = RGBColor(0xF0, 0xF4, 0xF8)
        card.line.color.rgb = RGBColor(0xD0, 0xD8, 0xE0)
        tf = card.text_frame
        tf.word_wrap = True
        p0 = tf.paragraphs[0]
        p0.alignment = PP_ALIGN.CENTER
        _set_run(p0.add_run(), str(value), size=24, color=NAVY, bold=True)
        p1 = tf.add_paragraph()
        p1.alignment = PP_ALIGN.CENTER
        _set_run(p1.add_run(), label, size=12, color=ACCENT)
    return slide


def _add_image_slide(prs, title, image_path):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    title_box = slide.shapes.add_textbox(Inches(0.6), Inches(0.4), Inches(9.0), Inches(0.8))
    _set_run(title_box.text_frame.paragraphs[0].add_run(), title, size=26, color=NAVY, bold=True)
    slide.shapes.add_picture(image_path, Inches(1.5), Inches(1.4), height=Inches(4.6))
    return slide


def build_pptx(state: dict, output_path: str) -> str:
    prs = Presentation()
    prs.slide_width = Inches(10)
    prs.slide_height = Inches(5.625)

    kpis = state.get("kpis", {})
    _add_title_slide(
        prs,
        "Quarterly Business Report",
        "Auto-generated by multi-agent GenAI pipeline",
    )

    kpi_cards = [
        ("Total Revenue", f"${kpis.get('total_revenue', 0):,}"),
        ("Total Units Sold", f"{kpis.get('total_units_sold', 0):,}"),
        ("Q1→Q4 Growth", f"{kpis.get('q1_to_q4_revenue_growth_pct', 'N/A')}%"),
        ("Top Region", kpis.get("top_region_by_revenue", "N/A")),
    ]
    _add_kpi_slide(prs, "Key Performance Indicators", kpi_cards)

    if state.get("data_findings"):
        _add_bullet_slide(prs, "Data Findings", state["data_findings"])

    chart_paths = state.get("chart_image_paths", [])
    if chart_paths:
        _add_image_slide(prs, "Supporting Chart", chart_paths[0])

    if state.get("vision_findings"):
        _add_bullet_slide(prs, "Chart & Document Findings", state["vision_findings"])

    if state.get("inferences"):
        _add_bullet_slide(prs, "Inferences & Recommendations", state["inferences"])

    prs.save(output_path)
    return output_path
